### ISSUE TITLE
Realizar diagrama de espina de pescado

### ISSUE THREAD

**Issue by 3morales04** [valen715/equipo7_cm_ppi2020#2]

**Comment by 3morales04** [comment]
![espina de pescado](https://user-images.githubusercontent.com/55636845/85079947-99f9a000-b18d-11ea-9e37-ac3df783646a.png)

**Comment by marthaduque** [comment]
revisar ortografía.

**Comment by 3morales04** [comment]
![espina de pescado](https://user-images.githubusercontent.com/55636845/87110617-15022380-c22d-11ea-96ba-52496f8bfa06.png)
