### ISSUE TITLE
Realizar validaciones con 5 usuarios (2)

### ISSUE THREAD

**Issue by 3morales04** [valen715/equipo7_cm_ppi2020#21]

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/88994039-11524180-d2ad-11ea-9f8c-fdd587538f49.png)

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/88994794-c46f6a80-d2ae-11ea-9818-fe863c375f3b.png)

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/88994808-ccc7a580-d2ae-11ea-9eee-c2e7a713a515.png)

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/88994823-d7823a80-d2ae-11ea-8f4a-69d192f75366.png)

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/88995702-faade980-d2b0-11ea-8de3-ff45a16aa847.png)

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/88995718-06011500-d2b1-11ea-8147-7760ba843563.png)

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/88995735-0ef1e680-d2b1-11ea-8082-b40c06cf2b6b.png)
