### ISSUE TITLE
Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by valentina-pulgarin** [valen715/equipo7_cm_ppi2020#27]

**Comment by valentina-pulgarin** [comment]
![WhatsApp Image 2020-09-09 at 11 01 07 PM](https://user-images.githubusercontent.com/66484253/92938624-65a32200-f412-11ea-9789-ae0d6d94aa1e.jpeg)

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/94873888-1438f200-0416-11eb-9310-b91eace93e89.png)

**Comment by juanfers1** [comment]
![image](https://user-images.githubusercontent.com/54716226/94874022-78f44c80-0416-11eb-9f52-8c6f5890ae89.png)
