### ISSUE TITLE
Definir los servicios de Backend que se deben implementar de acuerdo con las reglas de negocio (objetos JSON)

### ISSUE THREAD

**Issue by valentina-pulgarin** [valen715/equipo7_cm_ppi2020#28]

**Comment by 3morales04** [comment]
![WhatsApp Image 2020-10-16 at 9 28 14 AM](https://user-images.githubusercontent.com/55636845/96271075-11034180-0f92-11eb-9f0e-f454c46caf76.jpeg)

**Comment by 3morales04** [comment]
![WhatsApp Image 2020-10-16 at 9 29 28 AM](https://user-images.githubusercontent.com/55636845/96271266-4ad44800-0f92-11eb-90fa-38603f5f3051.jpeg)

**Comment by 3morales04** [comment]
![servicios1](https://user-images.githubusercontent.com/55636845/97522032-d378be00-196c-11eb-93ea-458a15defa18.png)
![servicios2](https://user-images.githubusercontent.com/55636845/97522025-d1aefa80-196c-11eb-9d47-45783ba15bb7.png)
![servicios3](https://user-images.githubusercontent.com/55636845/97522027-d2479100-196c-11eb-8d99-c8eea99b3d58.png)
