### ISSUE TITLE
Diseño del modelo lógico de datos

### ISSUE THREAD

**Issue by valentina-pulgarin** [valen715/equipo7_cm_ppi2020#29]

**Comment by 3morales04** [comment]
![WhatsApp Image 2020-11-26 at 6 35 10 PM](https://user-images.githubusercontent.com/55636845/100397200-70835100-3016-11eb-8710-4b879f084456.jpeg)

**Comment by 3morales04** [comment]
![WhatsApp Image 2020-11-26 at 6 45 28 PM](https://user-images.githubusercontent.com/55636845/100397437-ad9c1300-3017-11eb-8b42-60627d992557.jpeg)
