### ISSUE TITLE
Construir los servicios principales de Backend que se deben implementar de acuerdo con las reglas de negocio y conectarlo con la Base de datos

### ISSUE THREAD

**Issue by valentina-pulgarin** [valen715/equipo7_cm_ppi2020#31]

**Comment by 3morales04** [comment]
![WhatsApp Image 2020-11-26 at 8 06 11 PM](https://user-images.githubusercontent.com/55636845/100399989-eb526900-3022-11eb-825b-f2f19b272bfa.jpeg)
![WhatsApp Image 2020-11-26 at 8 06 41 PM](https://user-images.githubusercontent.com/55636845/100400004-f7d6c180-3022-11eb-90c4-9c94994afd89.jpeg)
