### ISSUE TITLE
Hacer tablero de visión del producto

### ISSUE THREAD

**Issue by 3morales04** [valen715/equipo7_cm_ppi2020#5]

**Comment by 3morales04** [comment]
Visión del proyecto
Es un servicio para personas con ingresos que se les dificulta planificar su dinero en sus necesidades o gastos, se llama “Afiline” es un aplicativo web  que les enseñará a manejar su salario de forma más adecuada para que así vayan creando poco a poco un hábito de ahorro a diferencia de distintos modo manuales los  cuales no son totalmente efectivos, nuestro producto se encarga de recordarte cuándo y cuánto debería pagar por cada deuda con solo ingresar tus ingresos mensuales y gastos.

**Comment by 3morales04** [comment]
![Sin título](https://user-images.githubusercontent.com/55636845/85782757-6a4a1b00-b6ec-11ea-8443-0fc8f80c496b.png)

**Comment by marthaduque** [comment]
Revisar la visión vs el alcance y ojo con el nombre del aplicativo, y corregir en las caracteristicas tambien teniendo en cuenta el alcance

**Comment by 3morales04** [comment]
![vision cuadro](https://user-images.githubusercontent.com/55636845/87107999-d5d0d400-c226-11ea-87ab-ca4f5512b2da.png)

**Comment by marthaduque** [comment]
En las caracteristicas del producto deben adicionar las funcionalidades del proyecto: " registrar  ingreso mensual del usuario y , gastos mensuales y generar  alerta cuando estos superen los ingresos"

**Comment by 3morales04** [comment]
![Identificacion 2](https://user-images.githubusercontent.com/55636845/88981745-4a2dee80-d28c-11ea-9e89-ebfdd8dc2c19.png)
