### ISSUE TITLE
Identificar y describir interesados

### ISSUE THREAD

**Issue by 3morales04** [valen715/equipo7_cm_ppi2020#6]

**Comment by 3morales04** [comment]
![Identificación de interesados 2](https://user-images.githubusercontent.com/55636845/85080201-2f952f80-b18e-11ea-930e-5660636120b9.png)
![Identificación de interesados](https://user-images.githubusercontent.com/55636845/85080202-302dc600-b18e-11ea-8fdb-dc49c63e06b3.png)

**Comment by marthaduque** [comment]
Corregir en la identificación de interesados el nombre empleados

**Comment by 3morales04** [comment]
![Sin título](https://user-images.githubusercontent.com/55636845/87109572-a754f800-c22a-11ea-8c10-0a578310b5af.png)
