### ISSUE TITLE
Declarar la situación del problema

### ISSUE THREAD

**Issue by 3morales04** [valen715/equipo7_cm_ppi2020#7]

**Comment by 3morales04** [comment]
Declaración de situación del problema
Actualmente en los hogares familiares colombianos, se suele no calcular y medir los ingresos (sueldos, consignaciones...etc) por ende, muchas familias buscan llevar a cabo maneras o métodos de ahorro con el fin de economizar estos, este problema normalmente esta asociados a la falta de conocimiento y llevar un control adecuado de ingresos y egresos sobre el registro del consumo realizado, puesto que quienes no conocen o no saben un método de ahorro adecuado tienden a perder una estabilidad económica.

**Comment by marthaduque** [comment]
corregir en la parte de estos...
